### ISSUE TITLE
Ace Jumper Activated

### ISSUE THREAD

**Issue by syntag** [lucax88x/CodeAceJumper#27]
When you activate Ace Jumper, would be nice to have a more visual activated state (as someone who likes to have their status bar visibility off).

I played around with the idea of adding a decorator to overlay the entire VS Code window and adding the following styles:
```css
.overlay {
    position: fixed;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background-color: #ffffff;
    mix-blend-mode: hue;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    pointer-events: none;
}
```

The code above will overlay the window and add a black-and-white effect to it. Would also be nice if the opacity of the black and white effect could be configurable by the user.
